### ISSUE TITLE
Broken since new YT UI update (YouTube Black Edition)

### ISSUE THREAD

**Issue by megakarlach** [BillyCool/UserStyles#1]
Since YouTube just rolled out a new major UI update, this userstyles is almost completely useless outside the search bar, the new YouTube UI isn't completely black after the update but its look more like darker gray if you look closely, or possibly, nearly pitch black which can make this useless.

**Comment by BillyCool** [comment]
Hey there! It is now be updated for the new YouTube UI and has a few new options to play with! Enjoy :)
